apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: reanafs
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 1
      requireSafeReplicaSize: false
  dataPools:
    - name: replicated
      replicated:
        size: 1
        requireSafeReplicaSize: false
  preserveFilesystemOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: false
