apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rook-cephfs-smoke
  namespace: __SMOKE_NAMESPACE__
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
