{{- if .Values.secrets.gitlab }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reana.prefix" . }}-cern-gitlab-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  REANA_GITLAB_OAUTH_APP_ID: {{ required "secrets.gitlab.REANA_GITLAB_OAUTH_APP_ID is required when secrets.gitlab is set" .Values.secrets.gitlab.REANA_GITLAB_OAUTH_APP_ID | b64enc }}
  REANA_GITLAB_OAUTH_APP_SECRET: {{ required "secrets.gitlab.REANA_GITLAB_OAUTH_APP_SECRET is required when secrets.gitlab is set" .Values.secrets.gitlab.REANA_GITLAB_OAUTH_APP_SECRET | b64enc }}
  REANA_GITLAB_HOST: {{ required "secrets.gitlab.REANA_GITLAB_HOST is required when secrets.gitlab is set" .Values.secrets.gitlab.REANA_GITLAB_HOST | b64enc }}
{{- end }}
