{{- if .Values.pgbouncer.enabled }}
{{- $dbUser := required "secrets.database.user must be set on first install (see database-secrets.yaml for details)." .Values.secrets.database.user }}
{{- $dbPassword := required "secrets.database.password must be set on first install (see database-secrets.yaml for details)." .Values.secrets.database.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reana.prefix" . }}-pgbouncer-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  userlist: {{ printf "%s %s" ($dbUser | quote) ($dbPassword | quote) | b64enc}}
{{- end }}
