{{- if .Values.secrets.cern.sso }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reana.prefix" . }}-cern-sso-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  CERN_CONSUMER_KEY: {{ required "secrets.cern.sso.CERN_CONSUMER_KEY is required when secrets.cern.sso is set" .Values.secrets.cern.sso.CERN_CONSUMER_KEY | b64enc }}
  CERN_CONSUMER_SECRET: {{ required "secrets.cern.sso.CERN_CONSUMER_SECRET is required when secrets.cern.sso is set" .Values.secrets.cern.sso.CERN_CONSUMER_SECRET | b64enc }}
{{- end }}
{{- if .Values.secrets.eosc.sso }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reana.prefix" . }}-eosc-sso-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  EOSC_CONSUMER_KEY: {{ required "secrets.eosc.sso.EOSC_CONSUMER_KEY is required when secrets.eosc.sso is set" .Values.secrets.eosc.sso.EOSC_CONSUMER_KEY | b64enc }}
  EOSC_CONSUMER_SECRET: {{ required "secrets.eosc.sso.EOSC_CONSUMER_SECRET is required when secrets.eosc.sso is set" .Values.secrets.eosc.sso.EOSC_CONSUMER_SECRET | b64enc }}
{{- end }}
