kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: manager
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
      - containerPort: 443
        hostPort: 443
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          certSANs:
          - "127.0.0.1"
          - "localhost"
          - "::1"
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
