# -*- coding: utf-8 -*-
#
# This file is part of REANA.
# Copyright (C) 2026 CERN.
#
# REANA is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Manage independent REANA source directories.

A source directory is a complete, independent copy of the REANA repository
collection.  Managed source directories are flat and may be named according to
their purpose, for example ``auth-audit``, ``broker-backoff``,
``condor-creds``, or ``dask-dashboard``.  Kitty and Tmux resolve session
targets by prefix, so srcdir names that differ early are quicker to switch
between.

The baseline is the canonical source directory.  Each managed copy is a
``srcdir``; several copies are ``srcdirs``.  A shell, Kitty session, or Tmux
session is merely an optional way to work in a srcdir, not part of its
identity.

The managed root defaults to a sibling of the canonical source directory and
subsequent commands discover it from marker files::

    reana-dev srcdir-create auth-audit
    reana-dev srcdir-workon auth-audit
    reana-dev srcdir-list
    reana-dev srcdir-rename auth-audit auth-api
    reana-dev srcdir-delete auth-api

Creation always copies the canonical source collection, removes copied local
branches, and resets each repository to its already-fetched ``master``
reference.  Remote-tracking references remain available, so branches and PRs
can then be composed with the existing ``git-checkout`` and
``git-checkout-pr`` commands.  Run ``reana-dev git-submodule --update`` after
composing branches so that ignored shared-module copies match them.
Creation uses copy-on-write when supported and a full archival copy otherwise.
Inside Kitty or Tmux, ``srcdir-workon`` uses a dedicated session named after
the srcdir.  Tmux takes precedence when both environments are present.  In
other terminals, it opens a shell in the current terminal.  Pass ``--kitty``,
``--tmux``, or ``--plain`` to override this auto-detection; ``--no-kitty``
and ``--no-tmux`` remain aliases for ``--plain``.  Kitty sessions are
generated as ``<name>.kitty-session`` under
``$XDG_DATA_HOME/kitty/sessions`` (or ``~/.local/share/kitty/sessions``),
renamed with the srcdir, and removed when it is deleted.  Only files carrying
the reana-dev ownership header are ever changed.
"""

import datetime
import hashlib
import json
import os
import platform
import re
import shlex
import shutil
import subprocess
import tempfile
from concurrent import futures
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple

import click

from reana.config import (
    COMPONENTS_USING_SHARED_MODULE_COMMONS,
    COMPONENTS_USING_SHARED_MODULE_DB,
    GIT_DEFAULT_BASE_BRANCH,
)

SRCDIR_MARKER = ".reana-srcdir.json"
SRCDIR_POINTER = ".reana-srcdirs"
SRCDIR_ROOT_MARKER = ".reana-srcdirs.json"
SRCDIR_MARKER_VERSION = 1
MISE_LOCAL_CONFIG = "mise.local.toml"
# The first line marks the file as managed: generated configurations are
# refreshed automatically, while configurations without a recognised header
# are left alone.  Keep former headers recognised so existing srcdirs migrate.
MISE_LOCAL_CONFIG_HEADER = "# Managed by reana-dev; delete this line to customise.\n"
MISE_LOCAL_CONFIG_LEGACY_HEADERS = ("# Generated by reana-dev srcdir-create.\n",)
RETENTION_REMOTES = ("local", "origin", "upstream")
TMUX_SRCDIR_OPTION = "@reana-srcdir"
TmuxSession = Tuple[str, Optional[str], Optional[str]]
KITTY_SESSION_HEADER = "# Managed by reana-dev srcdir-workon.\n"
KITTY_SESSION_OWNER_PREFIX = "# REANA srcdir: "
KITTY_SRCDIR_VAR = "srcdir"
OUTPUT_FIELD_WIDTH = 13


class SrcdirError(click.ClickException):
    """Render srcdir command failures with a red semantic label."""

    def show(self, file=None) -> None:
        """Print the failure while keeping its explanatory text unstyled."""
        if file is None:
            file = click.get_text_stream("stderr")
        click.secho("Error:", fg="red", nl=False, file=file, color=self.show_color)
        click.echo(f" {self.format_message()}", file=file, color=self.show_color)


@click.group()
def srcdir_commands():
    """REANA source directory commands group."""


def _echo_prefixed(
    prefix: str, message: str, colour: str, *, bold_message: bool = False
) -> None:
    """Print a semantic status line that remains clear without colour."""
    click.secho(prefix, fg=colour, nl=False)
    click.echo(" ", nl=False)
    if bold_message:
        click.secho(message, bold=True)
    else:
        click.echo(message)


def _echo_heading(message: str) -> None:
    """Print an informational or operation heading."""
    _echo_prefixed("==>", message, "blue", bold_message=True)


def _echo_success(message: str) -> None:
    """Print a successfully completed operation."""
    _echo_prefixed("✓", message, "green")


def _echo_warning(message: str) -> None:
    """Print a warning with a stable textual prefix."""
    _echo_prefixed("Warning:", message, "yellow")


def _echo_field(label: str, value: str) -> None:
    """Print one aligned summary or detail field."""
    click.echo(f"{label:<{OUTPUT_FIELD_WIDTH}}", nl=False)
    click.echo(value)


def _echo_command(command: str) -> None:
    """Print a suggested shell command."""
    click.secho("$ ", fg="cyan", nl=False)
    click.echo(command)


def _path(path: str) -> Path:
    """Return an absolute, normalised path."""
    return Path(path).expanduser().resolve()


def _is_within(path: Path, parent: Path) -> bool:
    """Return whether ``path`` is located inside ``parent``."""
    try:
        return os.path.commonpath([str(path), str(parent)]) == str(parent)
    except ValueError:
        return False


def _find_upwards(filename: str, start: Optional[Path] = None) -> Optional[Path]:
    """Find ``filename`` in the current directory or one of its parents."""
    current = (start or Path.cwd()).resolve()
    for directory in (current,) + tuple(current.parents):
        candidate = directory / filename
        if candidate.is_file():
            return candidate
    return None


def _read_json(path: Path) -> Dict:
    """Read and validate a versioned JSON marker."""
    try:
        with path.open(encoding="utf-8") as stream:
            data = json.load(stream)
    except (OSError, json.JSONDecodeError) as error:
        raise SrcdirError(f"Cannot read {path}: {error}") from error
    if not isinstance(data, dict):
        raise SrcdirError(f"Expected a JSON object in {path}.")
    if data.get("version") != SRCDIR_MARKER_VERSION:
        raise SrcdirError(
            f"Unsupported marker version in {path}: {data.get('version')!r}."
        )
    return data


def _required_marker_path(marker: Dict, field: str, marker_path: Path) -> Path:
    """Return a required absolute path from a marker."""
    value = marker.get(field)
    if not isinstance(value, str) or not value:
        raise SrcdirError(f"Missing {field!r} in {marker_path}.")
    return _path(value)


def _write_json(path: Path, data: Dict) -> None:
    """Write a JSON marker atomically."""
    temporary_path = path.with_name(f".{path.name}.tmp")
    try:
        with temporary_path.open("w", encoding="utf-8") as stream:
            json.dump(data, stream, indent=2, sort_keys=True)
            stream.write("\n")
        os.replace(temporary_path, path)
    except OSError as error:
        try:
            temporary_path.unlink()
        except FileNotFoundError:
            pass
        raise SrcdirError(f"Cannot write {path}: {error}") from error


def _validate_source_root(source_root: Path) -> None:
    """Validate a canonical REANA source collection root."""
    reana_git = source_root / "reana" / ".git"
    if not reana_git.is_dir():
        raise SrcdirError(
            f"{source_root} is not a REANA source directory: "
            "reana/.git is missing or is not a directory."
        )


def _discover_source_root(start: Optional[Path] = None) -> Path:
    """Discover a REANA source collection from the current directory."""
    current = (start or Path.cwd()).resolve()
    for directory in (current,) + tuple(current.parents):
        if (directory / "reana" / ".git").is_dir():
            return directory
        if directory.name == "reana" and (directory / ".git").is_dir():
            candidate = directory.parent
            if (candidate / "reana" / ".git").is_dir():
                return candidate
    raise SrcdirError(
        "Cannot discover a REANA source directory. Run the command from a "
        "REANA source directory or pass --source-root/--srcdir-root."
    )


def _load_task_context() -> Optional[Tuple[Path, Path]]:
    """Return canonical roots from the nearest task marker."""
    marker_path = _find_upwards(SRCDIR_MARKER)
    if marker_path is None:
        return None
    marker = _read_json(marker_path)
    source_root = _required_marker_path(marker, "source_root", marker_path)
    srcdir_root = _required_marker_path(marker, "srcdir_root", marker_path)
    if marker_path.parent.resolve().parent != srcdir_root:
        raise SrcdirError(f"Task marker {marker_path} does not describe a flat srcdir.")
    return source_root, srcdir_root


def _read_root_context(marker_path: Path) -> Tuple[Path, Path]:
    """Return canonical roots from a root marker."""
    marker = _read_json(marker_path)
    source_root = _required_marker_path(marker, "source_root", marker_path)
    srcdir_root = _required_marker_path(marker, "srcdir_root", marker_path)
    if marker_path.parent.resolve() != srcdir_root:
        raise SrcdirError(
            f"Source-directory root marker {marker_path} points elsewhere."
        )
    return source_root, srcdir_root


def _load_root_context() -> Optional[Tuple[Path, Path]]:
    """Return canonical roots from the nearest root marker."""
    marker_path = _find_upwards(SRCDIR_ROOT_MARKER)
    return _read_root_context(marker_path) if marker_path else None


def _load_root_context_at(srcdir_root: Path) -> Optional[Tuple[Path, Path]]:
    """Return canonical roots from an explicitly selected root."""
    marker_path = srcdir_root / SRCDIR_ROOT_MARKER
    return _read_root_context(marker_path) if marker_path.is_file() else None


def _load_source_pointer(source_root: Path) -> Optional[Path]:
    """Return a configured srcdir root from the canonical source directory."""
    pointer_path = source_root / SRCDIR_POINTER
    if not pointer_path.is_file():
        return None
    pointer = _read_json(pointer_path)
    return _required_marker_path(pointer, "srcdir_root", pointer_path)


def _resolve_context(
    source_root_option: Optional[str] = None,
    srcdir_root_option: Optional[str] = None,
    require_source: bool = True,
) -> Tuple[Path, Path]:
    """Resolve canonical source and managed-srcdir roots safely."""
    task_context = _load_task_context()
    explicit_root = _path(srcdir_root_option) if srcdir_root_option else None
    explicit_root_context = (
        _load_root_context_at(explicit_root) if explicit_root else None
    )
    root_context = explicit_root_context or _load_root_context()
    marker_context = task_context or root_context
    marker_source = marker_context[0] if marker_context else None
    marker_root = marker_context[1] if marker_context else None

    if source_root_option:
        source_root = _path(source_root_option)
        if marker_source and source_root != marker_source:
            raise SrcdirError(
                f"--source-root {source_root} conflicts with the discovered "
                f"canonical source directory {marker_source}."
            )
    elif marker_source:
        source_root = marker_source
    else:
        source_root = _discover_source_root()
    if require_source:
        _validate_source_root(source_root)

    configured_root = (
        _load_source_pointer(source_root) if source_root.is_dir() else None
    )
    if explicit_root:
        srcdir_root = explicit_root
        if marker_root and srcdir_root != marker_root:
            raise SrcdirError(
                f"--srcdir-root {srcdir_root} conflicts with the discovered "
                f"managed source-directory root {marker_root}."
            )
        if configured_root and srcdir_root != configured_root:
            raise SrcdirError(
                f"--srcdir-root {srcdir_root} conflicts with {configured_root} "
                f"recorded in {source_root / SRCDIR_POINTER}."
            )
    elif marker_root:
        srcdir_root = marker_root
    elif configured_root:
        srcdir_root = configured_root
    else:
        srcdir_root = source_root.parent / f"{source_root.name}-srcdirs"

    if srcdir_root == source_root or _is_within(srcdir_root, source_root):
        raise SrcdirError(
            f"Managed source-directory root {srcdir_root} cannot be located "
            f"inside canonical source directory {source_root}."
        )
    return source_root, srcdir_root


def _initialise_registry(source_root: Path, srcdir_root: Path) -> None:
    """Create and cross-link the canonical source and srcdir roots."""
    try:
        srcdir_root.mkdir(parents=True, exist_ok=True)
    except OSError as error:
        raise SrcdirError(f"Cannot create {srcdir_root}: {error}") from error

    root_marker_path = srcdir_root / SRCDIR_ROOT_MARKER
    if root_marker_path.exists():
        marker_source, marker_root = _read_root_context(root_marker_path)
        if marker_source != source_root or marker_root != srcdir_root:
            raise SrcdirError(
                f"{srcdir_root} is already associated with another source directory."
            )

    _write_json(
        root_marker_path,
        {
            "source_root": str(source_root),
            "srcdir_root": str(srcdir_root),
            "version": SRCDIR_MARKER_VERSION,
        },
    )
    _write_json(
        source_root / SRCDIR_POINTER,
        {"srcdir_root": str(srcdir_root), "version": SRCDIR_MARKER_VERSION},
    )


def _validate_name(name: str, param_hint: str = "NAME") -> None:
    """Validate a flat source-directory name."""
    if not name or name in {".", ".."}:
        raise click.BadParameter(
            "must be a non-empty directory name", param_hint=param_hint
        )
    separators = [separator for separator in (os.sep, os.altsep) if separator]
    if Path(name).name != name or any(separator in name for separator in separators):
        raise click.BadParameter(
            "must be one flat directory name without path separators",
            param_hint=param_hint,
        )


def _discover_repositories(source_root: Path) -> List[str]:
    """Return top-level Git repositories and reject linked worktrees."""
    repositories = []
    for candidate in sorted(source_root.iterdir()):
        git_path = candidate / ".git"
        if git_path.is_file():
            raise SrcdirError(
                f"Cannot copy {source_root}: {candidate.name}/.git is a file, "
                "which indicates a linked Git worktree."
            )
        registered_worktrees = git_path / "worktrees"
        if registered_worktrees.is_dir() and any(registered_worktrees.iterdir()):
            raise SrcdirError(
                f"Cannot copy {source_root}: {candidate.name} has registered "
                "linked Git worktrees. Remove active worktrees, or run "
                f"git -C {shlex.quote(str(candidate))} worktree prune if the "
                "registrations are stale."
            )
        if candidate.is_dir() and git_path.is_dir():
            repositories.append(candidate.name)
    if "reana" not in repositories:
        raise SrcdirError(f"No reana Git repository found in {source_root}.")
    return repositories


def _run(
    arguments: List[str], cwd: Optional[Path] = None, check: bool = True
) -> subprocess.CompletedProcess:
    """Run a subprocess and turn failures into Click errors."""
    result = subprocess.run(
        arguments,
        cwd=str(cwd) if cwd else None,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if check and result.returncode:
        details = (result.stderr or result.stdout).strip()
        message = f"Command failed ({' '.join(arguments)})"
        if details:
            message += f": {details}"
        raise SrcdirError(message)
    return result


def _darwin_filesystem(path: Path) -> Optional[str]:
    """Return the Darwin filesystem type containing ``path``."""
    df_result = _run(["df", "-P", str(path)], check=False)
    if df_result.returncode or not df_result.stdout.splitlines():
        return None
    fields = df_result.stdout.splitlines()[-1].split(maxsplit=5)
    if len(fields) != 6:
        return None
    mountpoint = fields[-1]
    mount_result = _run(["mount"], check=False)
    if mount_result.returncode:
        return None
    marker = f" on {mountpoint} ("
    for line in mount_result.stdout.splitlines():
        if marker in line:
            return line.split(marker, 1)[1].split(",", 1)[0].rstrip(")")
    return None


def _linux_reflink_supported(source_root: Path, destination_parent: Path) -> bool:
    """Probe reflink support between the source and destination filesystems."""
    probe_source = source_root / "reana" / ".git" / "HEAD"
    with tempfile.TemporaryDirectory(
        prefix=".reana-srcdir-reflink-", dir=str(destination_parent)
    ) as probe_directory:
        probe_destination = Path(probe_directory) / "HEAD"
        result = _run(
            [
                "cp",
                "--reflink=always",
                str(probe_source),
                str(probe_destination),
            ],
            check=False,
        )
    return result.returncode == 0


def _source_disk_usage(source_root: Path) -> Optional[int]:
    """Return the source's allocated size in bytes when ``du`` succeeds."""
    result = _run(["du", "-sk", str(source_root)], check=False)
    if result.returncode:
        return None
    try:
        return int(result.stdout.split()[0]) * 1024
    except (IndexError, ValueError):
        return None


def _format_disk_usage(size: int) -> str:
    """Format a byte count for a concise copy-strategy announcement."""
    if size >= 1024**3:
        return f"{size / 1024**3:.1f} GiB"
    if size >= 1024**2:
        return f"{size / 1024**2:.0f} MiB"
    if size >= 1024:
        return f"{size / 1024:.0f} KiB"
    return f"{size} B"


def _copy_source_directory(source_root: Path, destination: Path) -> None:
    """Copy a source collection after announcing the selected strategy."""
    if platform.system() == "Darwin":
        filesystems = {
            _darwin_filesystem(source_root),
            _darwin_filesystem(destination.parent),
        }
        use_clone = filesystems == {"apfs"} and (
            source_root.stat().st_dev == destination.parent.stat().st_dev
        )
        arguments = [
            "cp",
            "-ac" if use_clone else "-a",
            str(source_root),
            str(destination),
        ]
        copy_on_write = use_clone
    elif platform.system() == "Linux":
        copy_on_write = _linux_reflink_supported(source_root, destination.parent)
        arguments = [
            "cp",
            "--archive",
            f"--reflink={'always' if copy_on_write else 'never'}",
            str(source_root),
            str(destination),
        ]
    else:
        copy_on_write = False
        arguments = ["cp", "-a", str(source_root), str(destination)]

    if copy_on_write:
        strategy = "copy-on-write clone"
    else:
        size = _source_disk_usage(source_root)
        size_note = f", about {_format_disk_usage(size)}" if size is not None else ""
        strategy = f"full copy{size_note}"
    _echo_heading("Copying source collection")
    _echo_field("Strategy", strategy)
    _echo_field("Source", str(source_root))
    _echo_field("Destination", str(destination))
    _run(arguments)


def _git(repository: Path, *arguments: str, check: bool = True) -> str:
    """Run Git in a repository and return stripped standard output."""
    result = _run(["git", *arguments], cwd=repository, check=check)
    return result.stdout.strip()


def _git_ref_exists(repository: Path, reference: str) -> bool:
    """Return whether a Git reference exists."""
    result = _run(
        ["git", "show-ref", "--verify", "--quiet", reference],
        cwd=repository,
        check=False,
    )
    return result.returncode == 0


def _remove_non_default_local_branches(repository: Path) -> None:
    """Remove copied local branches other than the default branch."""
    local_ref_prefix = "refs/heads/"
    branch_refs = _git(
        repository,
        "for-each-ref",
        "--format=%(refname)",
        "refs/heads",
    ).splitlines()
    branches_to_remove = [
        branch_ref[len(local_ref_prefix) :]
        for branch_ref in branch_refs
        if branch_ref != f"{local_ref_prefix}{GIT_DEFAULT_BASE_BRANCH}"
    ]
    if branches_to_remove:
        _git(
            repository,
            "branch",
            "--delete",
            "--force",
            "--",
            *branches_to_remove,
        )


def _prepare_repository(
    destination_root: Path, source_root: Path, repository_name: str
) -> None:
    """Reset a copied repository to clean, single-branch master."""
    repository = destination_root / repository_name
    references = (
        f"refs/remotes/upstream/{GIT_DEFAULT_BASE_BRANCH}",
        f"refs/remotes/origin/{GIT_DEFAULT_BASE_BRANCH}",
        f"refs/heads/{GIT_DEFAULT_BASE_BRANCH}",
    )
    reference = next(
        (
            candidate
            for candidate in references
            if _git_ref_exists(repository, candidate)
        ),
        None,
    )
    if reference is None:
        raise SrcdirError(
            f"Cannot initialise {repository_name}: no {GIT_DEFAULT_BASE_BRANCH} "
            "reference exists."
        )
    _git(
        repository,
        "checkout",
        "--force",
        "-B",
        GIT_DEFAULT_BASE_BRANCH,
        reference,
    )
    _git(repository, "clean", "-ffd")
    _remove_non_default_local_branches(repository)
    _git(repository, "remote", "remove", "local", check=False)
    _git(repository, "remote", "add", "local", str(source_root / repository_name))
    _git(repository, "fetch", "--quiet", "--prune", "local")


def _sync_shared_module(
    destination_root: Path, module: str, components: List[str]
) -> None:
    """Synchronise one shared module into copied component directories."""
    module_source = destination_root / module
    if not module_source.is_dir():
        return
    for component in components:
        component_root = destination_root / component
        if component_root.is_dir():
            _run(
                [
                    "rsync",
                    "-az",
                    "--delete",
                    "--exclude=.git",
                    "--exclude=.mise.toml",
                    "--exclude=mise.local.toml",
                    str(module_source),
                    str(component_root / "modules"),
                ]
            )


def _sync_shared_modules(destination_root: Path) -> None:
    """Synchronise all derived shared-module directories."""
    if shutil.which("rsync") is None:
        raise SrcdirError(
            "Cannot synchronise shared modules because rsync is not installed."
        )
    _sync_shared_module(
        destination_root,
        "reana-commons",
        COMPONENTS_USING_SHARED_MODULE_COMMONS,
    )
    _sync_shared_module(
        destination_root,
        "reana-db",
        COMPONENTS_USING_SHARED_MODULE_DB,
    )


def _tmux_session_name(
    name: str, existing_names: Optional[Dict[str, str]] = None
) -> str:
    """Return a target-safe and unique Tmux session name."""
    safe_name = re.sub(r"[^A-Za-z0-9_-]+", "-", name).strip("-") or "srcdir"
    owners = existing_names or {}
    candidate = safe_name
    owner = owners.get(candidate)
    if owner is not None and owner != name:
        digest = hashlib.sha256(name.encode()).hexdigest()[:8]
        candidate = f"{candidate}-{digest}"
        owner = owners.get(candidate)
        if owner is not None and owner != name:
            candidate = f"{safe_name}-{hashlib.sha256(name.encode()).hexdigest()}"
    return candidate


def _legacy_tmux_session_name(name: str, session_name: Optional[str]) -> bool:
    """Return whether a marker contains the former ``reana-*`` name shape."""
    safe_name = re.sub(r"[^A-Za-z0-9_-]+", "-", name).strip("-") or "srcdir"
    legacy_name = f"reana-{safe_name}"
    return bool(
        session_name == legacy_name
        or (session_name and session_name.startswith(f"{legacy_name}-"))
    )


def _existing_tmux_names(srcdir_root: Path) -> Dict[str, str]:
    """Return Tmux names already assigned to managed source directories."""
    names = {}
    if not srcdir_root.is_dir():
        return names
    for candidate in srcdir_root.iterdir():
        marker_path = candidate / SRCDIR_MARKER
        if marker_path.is_file():
            marker = _read_json(marker_path)
            if marker.get("tmux_session") and marker.get("name"):
                names[marker["tmux_session"]] = marker["name"]
    return names


def _allocated_tmux_names(
    srcdir_root: Path,
    sessions: Optional[Dict[str, TmuxSession]] = None,
) -> Dict[str, str]:
    """Return names reserved by srcdir markers and live Tmux sessions."""
    names = _existing_tmux_names(srcdir_root)
    live_sessions = _list_tmux_sessions() if sessions is None else sessions
    for session_name, (session_id, _, _) in live_sessions.items():
        names.setdefault(session_name, f"tmux:{session_id}")
    return names


def _mise_config_contents(destination: Path) -> str:
    """Return the generated mise override for a managed srcdir."""
    environment_name = json.dumps(destination.name, ensure_ascii=False)
    return (
        MISE_LOCAL_CONFIG_HEADER
        + "[env]\n"
        + '_.python.venv = { path = ".venv", create = true, '
        + 'uv_create_args = ["--seed", "--prompt", '
        + f"{environment_name}], "
        + 'python_create_args = ["--prompt", '
        + f"{environment_name}] }}\n"
    )


def _write_mise_config(destination: Path, overwrite: bool = False) -> Path:
    """Write the srcdir-specific mise virtual-environment override."""
    config_path = destination / MISE_LOCAL_CONFIG
    if config_path.exists() and not overwrite:
        raise SrcdirError(
            f"Cannot configure a per-srcdir virtual environment because "
            f"{config_path} already exists. Use --no-mise-venv or remove the "
            "source-level local override."
        )
    temporary_path = config_path.with_name(f".{config_path.name}.tmp")
    try:
        temporary_path.write_text(
            _mise_config_contents(destination),
            encoding="utf-8",
        )
        os.replace(temporary_path, config_path)
    except OSError as error:
        try:
            temporary_path.unlink()
        except FileNotFoundError:
            pass
        raise SrcdirError(f"Cannot write {config_path}: {error}") from error
    return config_path


def _mise_config_is_generated(contents: str) -> bool:
    """Return whether mise configuration is managed by reana-dev."""
    headers = (MISE_LOCAL_CONFIG_HEADER,) + MISE_LOCAL_CONFIG_LEGACY_HEADERS
    return contents.startswith(headers)


def _refresh_mise_config(destination: Path) -> bool:
    """Refresh a stale generated mise override and report any change."""
    config_path = destination / MISE_LOCAL_CONFIG
    try:
        current_contents = config_path.read_text(encoding="utf-8")
    except OSError as error:
        raise SrcdirError(f"Cannot read {config_path}: {error}") from error
    if not _mise_config_is_generated(current_contents):
        return False
    if current_contents == _mise_config_contents(destination):
        return False
    _write_mise_config(destination, overwrite=True)
    return True


def _install_reana_dev(destination: Path) -> None:
    """Install reana-dev and release tools in a managed environment."""
    _run(
        [
            "mise",
            "exec",
            "-C",
            str(destination),
            "--",
            "python",
            "-m",
            "pip",
            "install",
            "--editable",
            f"{destination / 'reana'}[release]",
        ]
    )


def _bootstrap_mise(destination: Path) -> None:
    """Create, trust, and populate a mise-managed virtual environment."""
    root_config = destination / ".mise.toml"
    local_config = _write_mise_config(destination)
    if root_config.is_file():
        _run(["mise", "trust", str(root_config)])
    _run(["mise", "trust", str(local_config)])
    _install_reana_dev(destination)
    expected_command = destination / ".venv" / "bin" / "reana-dev"
    if not expected_command.is_file():
        raise SrcdirError(
            f"Virtual environment bootstrap did not create {expected_command}."
        )


def _should_use_mise(source_root: Path, mise_venv: Optional[bool]) -> bool:
    """Resolve the tri-state mise virtual-environment option."""
    mise_available = shutil.which("mise") is not None
    root_config_exists = (source_root / ".mise.toml").is_file()
    if mise_venv is True and not mise_available:
        raise SrcdirError("--mise-venv requires the mise executable.")
    if mise_venv is True and not root_config_exists:
        raise SrcdirError(f"--mise-venv requires {source_root / '.mise.toml'}.")
    if mise_venv is None and root_config_exists and not mise_available:
        _echo_warning(
            "Skipping the per-srcdir virtual environment because mise is not installed.",
        )
    return mise_venv is True or (
        mise_venv is None and mise_available and root_config_exists
    )


def _task_marker(destination: Path) -> Dict:
    """Read and validate a task marker at an expected flat destination."""
    marker_path = destination / SRCDIR_MARKER
    if not marker_path.is_file():
        raise SrcdirError(f"No managed source directory at {destination}.")
    marker = _read_json(marker_path)
    if marker.get("name") != destination.name:
        raise SrcdirError(f"Marker name does not match {destination}.")
    marker_root = _required_marker_path(marker, "srcdir_root", marker_path)
    if marker_root != destination.parent.resolve():
        raise SrcdirError(f"Marker root does not match {destination}.")
    return marker


@click.argument("name")
@click.option(
    "--source-root",
    type=click.Path(file_okay=False),
    help="Canonical REANA source directory [optional; auto-discovered].",
)
@click.option(
    "--srcdir-root",
    type=click.Path(file_okay=False),
    help=(
        "Directory containing managed source directories "
        "[optional; auto-discovered]."
    ),
)
@click.option(
    "--mise-venv/--no-mise-venv",
    default=None,
    help="Create a mise-managed virtual environment [optional; auto-detected].",
)
@srcdir_commands.command(name="srcdir-create")
def srcdir_create(
    name: str,
    source_root: Optional[str],
    srcdir_root: Optional[str],
    mise_venv: Optional[bool],
) -> None:
    """Create a clean, master-based source directory called NAME.

    Prefer copy-on-write and use a full archival copy when it is unavailable.
    Copied local branches are removed; explicitly requested branches can still
    be restored using reana-dev git-checkout or git-checkout-pr.

    Tmux resolves session targets by prefix, so srcdir names that differ early
    are quicker to switch between.
    """
    _validate_name(name)
    canonical_source, managed_root = _resolve_context(source_root, srcdir_root)
    repositories = _discover_repositories(canonical_source)
    _initialise_registry(canonical_source, managed_root)
    destination = managed_root / name
    if destination.exists():
        raise SrcdirError(f"Destination already exists: {destination}")

    use_mise = _should_use_mise(canonical_source, mise_venv)
    marker = {
        "created_at": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "initial_heads": {},
        "name": name,
        "python_environment": "mise" if use_mise else None,
        "repositories": repositories,
        "source_root": str(canonical_source),
        "srcdir_root": str(managed_root),
        "state": "creating",
        "kitty_session": str(_kitty_session_path(name)),
        "tmux_session": _tmux_session_name(
            name, existing_names=_allocated_tmux_names(managed_root)
        ),
        "version": SRCDIR_MARKER_VERSION,
    }

    _echo_heading(f"Creating srcdir {name}")
    try:
        _copy_source_directory(canonical_source, destination)
        _write_json(destination / SRCDIR_MARKER, marker)
        _echo_heading(f"Preparing {len(repositories)} repositories")
        for repository in repositories:
            _prepare_repository(destination, canonical_source, repository)
        _sync_shared_modules(destination)
        marker["initial_heads"] = {
            repository: _git(destination / repository, "rev-parse", "HEAD")
            for repository in repositories
        }
        if use_mise:
            _echo_heading(f"Creating Python environment {name}")
            _bootstrap_mise(destination)
        marker["state"] = "ready"
        _write_json(destination / SRCDIR_MARKER, marker)
    except BaseException:
        if destination.is_dir():
            try:
                shutil.rmtree(destination)
            except OSError as error:
                raise SrcdirError(
                    f"Creation failed and the incomplete source directory "
                    f"could not be removed: {destination}: {error}"
                ) from error
        raise

    click.echo()
    _echo_success(f"Created srcdir {name}")
    click.echo()
    _echo_field("Location", str(destination))
    _echo_field(
        "Repositories", f"{len(repositories)} (clean {GIT_DEFAULT_BASE_BRANCH})"
    )
    if use_mise:
        _echo_field("Environment", f"{name} ({destination / '.venv'})")
    click.echo()
    _echo_heading("Next steps:")
    _echo_command(f"reana-dev srcdir-workon {name}")
    _echo_command("reana-dev git-checkout-pr -i REPOSITORY ISSUE --pull --reset")
    _echo_command("reana-dev git-submodule --update")


def _list_tmux_sessions() -> Dict[str, TmuxSession]:
    """Return exact Tmux names mapped to IDs, owners, and session paths."""
    if shutil.which("tmux") is None:
        return {}
    result = _run(
        [
            "tmux",
            "list-sessions",
            "-F",
            f"#{{session_id}}\t#{{session_name}}\t"
            f"#{{{TMUX_SRCDIR_OPTION}}}\t#{{session_path}}",
        ],
        check=False,
    )
    if result.returncode:
        return {}
    sessions = {}
    for line in result.stdout.splitlines():
        fields = line.split("\t", 3)
        if len(fields) >= 2:
            session_id, session_name = fields[:2]
            owner = fields[2] if len(fields) >= 3 and fields[2] else None
            session_path = fields[3] if len(fields) == 4 and fields[3] else None
            sessions[session_name] = (session_id, owner, session_path)
    return sessions


def _owned_tmux_session_id(
    session_name: str,
    session: Optional[TmuxSession],
    destination: Path,
    allow_unmarked_legacy: bool = False,
) -> Optional[str]:
    """Return an owned ID, adopting an exact path match, or reject it."""
    if session is None:
        return None
    session_id, owner, session_path = session
    if owner is None and session_path and _path(session_path) == destination:
        # Persist ownership when first observing an intermediate-version session.
        _mark_tmux_session(session_id, destination)
        return session_id
    if _tmux_session_is_owned(session, destination, allow_unmarked_legacy):
        return session_id
    raise SrcdirError(
        f"Tmux session {session_name!r} is not owned by srcdir {destination}. "
        "Rename or stop the foreign session before continuing."
    )


def _tmux_session_is_owned(
    session: TmuxSession,
    destination: Path,
    allow_unmarked_legacy: bool = False,
) -> bool:
    """Return whether Tmux metadata identifies a session with a srcdir."""
    _, owner, session_path = session
    return bool(
        owner == str(destination)
        or (owner is None and session_path and _path(session_path) == destination)
        or (owner is None and allow_unmarked_legacy)
    )


def _mark_tmux_session(session_id: str, destination: Path) -> None:
    """Record the owning srcdir path on a Tmux session."""
    _run(
        [
            "tmux",
            "set-option",
            "-t",
            session_id,
            TMUX_SRCDIR_OPTION,
            str(destination),
        ]
    )


def _harmonise_tmux_session(
    destination: Path,
    marker: Dict,
    sessions: Dict[str, TmuxSession],
) -> Tuple[str, Optional[str]]:
    """Align a legacy Tmux session and marker with the srcdir name."""
    current_name = marker.get("tmux_session")
    current_session = sessions.get(current_name)
    allow_unmarked_legacy = _legacy_tmux_session_name(marker["name"], current_name)
    current_is_foreign = bool(
        current_session
        and not _tmux_session_is_owned(
            current_session,
            destination,
            allow_unmarked_legacy=allow_unmarked_legacy,
        )
    )
    allocated_names = _allocated_tmux_names(destination.parent, sessions)
    if current_is_foreign:
        allocated_names[current_name] = f"tmux:{current_session[0]}"
    desired_name = _tmux_session_name(
        marker["name"],
        existing_names=allocated_names,
    )
    desired_session = sessions.get(desired_name)
    current_id = (
        None
        if current_is_foreign
        else _owned_tmux_session_id(
            current_name,
            current_session,
            destination,
            allow_unmarked_legacy=allow_unmarked_legacy,
        )
    )
    if current_name == desired_name:
        return desired_name, current_id
    desired_id = _owned_tmux_session_id(desired_name, desired_session, destination)
    if desired_id is not None and desired_id != current_id:
        raise SrcdirError(
            f"Cannot migrate Tmux session {current_name!r} to {desired_name!r}: "
            "both sessions are already associated with this srcdir."
        )
    if current_id is not None:
        _run(["tmux", "rename-session", "-t", current_id, desired_name])
        _mark_tmux_session(current_id, destination)
        _echo_heading(f"Renamed Tmux session {current_name} to {desired_name}")
    marker["tmux_session"] = desired_name
    _write_json(destination / SRCDIR_MARKER, marker)
    return desired_name, current_id or desired_id


def _kitty_session_path(name: str) -> Path:
    """Return the generated Kitty session path for a srcdir name."""
    data_home = os.environ.get("XDG_DATA_HOME")
    base = _path(data_home) if data_home else Path.home() / ".local" / "share"
    return base / "kitty" / "sessions" / f"{name}.kitty-session"


def _kitty_remote_tree() -> Optional[List[Dict]]:
    """Return Kitty's remote-control tree, or ``None`` when unreachable."""
    listen_on = os.environ.get("KITTY_LISTEN_ON")
    if not listen_on or shutil.which("kitten") is None:
        return None
    result = _run(
        ["kitten", "@", "--to", listen_on, "ls"],
        check=False,
    )
    if result.returncode:
        return None
    try:
        tree = json.loads(result.stdout)
    except json.JSONDecodeError:
        return None
    return tree if isinstance(tree, list) else None


def _kitty_srcdir_sessions(tree: List[Dict]) -> Set[str]:
    """Return the srcdir paths that tagged Kitty windows belong to."""
    owners: Set[str] = set()

    def visit(value) -> None:
        if isinstance(value, list):
            for item in value:
                visit(item)
            return
        if not isinstance(value, dict):
            return
        user_vars = value.get("user_vars")
        if isinstance(user_vars, dict):
            owner = user_vars.get(KITTY_SRCDIR_VAR)
            if isinstance(owner, str) and owner:
                owners.add(owner)
        for child in value.values():
            if child is not user_vars:
                visit(child)

    visit(tree)
    return owners


def _kitty_session_owners(tree: List[Dict]) -> Dict[str, Set[str]]:
    """Return the tagged srcdir owners for each named Kitty session.

    Kitty reports ``session_name`` on individual windows rather than on their
    tab or OS window, and one OS window commonly holds tabs from several
    sessions, so pair every window's session with that window's own tag.
    """
    sessions: Dict[str, Set[str]] = {}

    def visit(value) -> None:
        if isinstance(value, list):
            for item in value:
                visit(item)
            return
        if not isinstance(value, dict):
            return
        user_vars = value.get("user_vars")
        session_name = value.get("session_name")
        if isinstance(session_name, str) and session_name:
            owners = sessions.setdefault(session_name, set())
            if isinstance(user_vars, dict):
                owner = user_vars.get(KITTY_SRCDIR_VAR)
                if isinstance(owner, str) and owner:
                    owners.add(owner)
        for child in value.values():
            if child is not user_vars:
                visit(child)

    visit(tree)
    return sessions


def _foreign_kitty_session(tree: List[Dict], name: str, destination: Path) -> bool:
    """Return whether NAME is live without belonging to DESTINATION."""
    sessions = _kitty_session_owners(tree)
    return name in sessions and str(destination) not in sessions[name]


def _list_kitty_sessions() -> Optional[Set[str]]:
    """Return tagged Kitty srcdir paths, or ``None`` when unavailable."""
    tree = _kitty_remote_tree()
    return _kitty_srcdir_sessions(tree) if tree is not None else None


def _warn_if_kitty_state_unknown(marker: Dict) -> None:
    """Warn when a generated session exists but Kitty cannot be queried."""
    if _marker_kitty_session_path(marker).exists():
        _echo_warning(
            "Cannot verify whether the Kitty session is running; run this "
            "command from a Kitty window with remote control enabled to check."
        )


def _kitty_session_contents(destination: Path, shell_arguments: List[str]) -> str:
    """Return a one-window Kitty session for a managed srcdir."""
    launch_arguments = [
        "--cwd",
        str(destination),
        "--var",
        f"{KITTY_SRCDIR_VAR}={destination}",
        *shell_arguments,
    ]
    return (
        KITTY_SESSION_HEADER
        + KITTY_SESSION_OWNER_PREFIX
        + json.dumps(str(destination), ensure_ascii=False)
        + "\nlaunch "
        + shlex.join(launch_arguments)
        + "\n"
    )


def _kitty_session_owner(contents: str) -> Optional[str]:
    """Return the srcdir owner recorded in a generated Kitty session."""
    lines = contents.splitlines()
    if not contents.startswith(KITTY_SESSION_HEADER) or len(lines) < 2:
        return None
    owner_line = lines[1]
    if not owner_line.startswith(KITTY_SESSION_OWNER_PREFIX):
        return None
    try:
        owner = json.loads(owner_line[len(KITTY_SESSION_OWNER_PREFIX) :])
    except json.JSONDecodeError:
        return None
    return owner if isinstance(owner, str) and owner else None


def _write_kitty_session(
    session_path: Path,
    destination: Path,
    shell_arguments: List[str],
) -> None:
    """Create or refresh a generated Kitty session without overwriting others."""
    if session_path.exists():
        try:
            current_contents = session_path.read_text(encoding="utf-8")
        except OSError as error:
            raise SrcdirError(f"Cannot read {session_path}: {error}") from error
        owner = _kitty_session_owner(current_contents)
        if owner != str(destination):
            explanation = (
                f"it belongs to {owner}" if owner else "it is not managed by reana-dev"
            )
            raise SrcdirError(
                f"Cannot replace Kitty session {session_path}: {explanation}."
            )
    _write_kitty_session_contents(
        session_path,
        _kitty_session_contents(destination, shell_arguments),
    )


def _write_kitty_session_contents(session_path: Path, contents: str) -> None:
    """Atomically write already-validated generated Kitty session contents."""
    temporary_path = session_path.with_name(f".{session_path.name}.tmp")
    try:
        session_path.parent.mkdir(parents=True, exist_ok=True)
        temporary_path.write_text(contents, encoding="utf-8")
        os.replace(temporary_path, session_path)
    except OSError as error:
        try:
            temporary_path.unlink()
        except FileNotFoundError:
            pass
        raise SrcdirError(f"Cannot write {session_path}: {error}") from error


def _marker_kitty_session_path(marker: Dict) -> Path:
    """Return a marker's Kitty session path, deriving it for older markers."""
    value = marker.get("kitty_session")
    if isinstance(value, str) and value:
        return _path(value)
    return _kitty_session_path(marker["name"])


def _renamed_kitty_session_contents(
    contents: str, source: Path, destination: Path
) -> str:
    """Retarget generated Kitty session contents after a srcdir rename."""
    old_path = str(source)
    new_path = str(destination)
    rewritten = []
    for index, line in enumerate(contents.splitlines()):
        if index == 1 and line.startswith(KITTY_SESSION_OWNER_PREFIX):
            rewritten.append(
                KITTY_SESSION_OWNER_PREFIX + json.dumps(new_path, ensure_ascii=False)
            )
            continue
        if line.startswith("launch "):
            try:
                arguments = shlex.split(line[len("launch ") :])
            except ValueError as error:
                raise SrcdirError(
                    f"Cannot parse generated Kitty session while renaming: {error}"
                ) from error
            replacements = {
                old_path: new_path,
                f"{KITTY_SRCDIR_VAR}={old_path}": f"{KITTY_SRCDIR_VAR}={new_path}",
            }
            arguments = [replacements.get(argument, argument) for argument in arguments]
            rewritten.append("launch " + shlex.join(arguments))
            continue
        rewritten.append(line)
    return "\n".join(rewritten) + "\n"


def _kitty_session_rename_plan(
    source: Path, destination: Path, marker: Dict, new_name: str
) -> Tuple[Path, Path, Optional[str], Optional[str]]:
    """Validate and prepare a generated Kitty session-file rename."""
    old_session_path = _marker_kitty_session_path(marker)
    new_session_path = _kitty_session_path(new_name)
    if new_session_path != old_session_path and new_session_path.exists():
        raise SrcdirError(f"Kitty session path already exists: {new_session_path}")
    if not old_session_path.exists():
        return old_session_path, new_session_path, None, None
    try:
        old_contents = old_session_path.read_text(encoding="utf-8")
    except OSError as error:
        raise SrcdirError(f"Cannot read {old_session_path}: {error}") from error
    owner = _kitty_session_owner(old_contents)
    if owner != str(source):
        explanation = (
            f"it belongs to {owner}" if owner else "it is not managed by reana-dev"
        )
        raise SrcdirError(
            f"Cannot rename Kitty session {old_session_path}: {explanation}."
        )
    new_contents = _renamed_kitty_session_contents(old_contents, source, destination)
    return old_session_path, new_session_path, old_contents, new_contents


def _validate_kitty_session_file(session_path: Path, destination: Path) -> bool:
    """Validate that a present Kitty session file belongs to a srcdir."""
    if not session_path.exists():
        return False
    try:
        contents = session_path.read_text(encoding="utf-8")
    except OSError as error:
        raise SrcdirError(f"Cannot read {session_path}: {error}") from error
    owner = _kitty_session_owner(contents)
    if owner != str(destination):
        explanation = (
            f"it belongs to {owner}" if owner else "it is not managed by reana-dev"
        )
        raise SrcdirError(f"Cannot remove Kitty session {session_path}: {explanation}.")
    return True


def _remove_kitty_session_file(session_path: Path, destination: Path) -> bool:
    """Remove a generated Kitty session file owned by a srcdir, if present."""
    if not _validate_kitty_session_file(session_path, destination):
        return False
    try:
        session_path.unlink()
    except OSError as error:
        raise SrcdirError(f"Cannot remove {session_path}: {error}") from error
    return True


def _ensure_kitty_session(
    destination: Path, marker: Dict, shell_arguments: List[str]
) -> Path:
    """Refresh Kitty's generated session file and marker metadata."""
    session_path = _kitty_session_path(marker["name"])
    _write_kitty_session(session_path, destination, shell_arguments)
    if marker.get("kitty_session") != str(session_path):
        marker["kitty_session"] = str(session_path)
        _write_json(destination / SRCDIR_MARKER, marker)
    return session_path


def _close_kitty_session(destination: Path) -> None:
    """Close all Kitty tabs tagged as belonging to a srcdir."""
    listen_on = os.environ.get("KITTY_LISTEN_ON")
    if not listen_on or shutil.which("kitten") is None:
        raise SrcdirError(
            "Cannot close the Kitty session: remote control is unavailable."
        )
    owner_pattern = re.escape(str(destination))
    _run(
        [
            "kitten",
            "@",
            "--to",
            listen_on,
            "close-tab",
            "--match",
            f"var:{KITTY_SRCDIR_VAR}=^{owner_pattern}$",
        ]
    )


def _ensure_mise_environment(destination: Path, marker: Dict) -> None:
    """Repair a missing mise environment before opening a srcdir."""
    if marker.get("python_environment") != "mise":
        return
    local_config = destination / MISE_LOCAL_CONFIG
    config_updated = (
        _refresh_mise_config(destination) if local_config.is_file() else False
    )
    if (
        local_config.is_file()
        and not config_updated
        and _mise_environment_ready(destination)
    ):
        return
    if shutil.which("mise") is None:
        raise SrcdirError(
            f"{destination} requires mise, but the mise executable is unavailable."
        )
    _discard_mise_environment(destination)
    root_config = destination / ".mise.toml"
    if not local_config.is_file():
        _bootstrap_mise(destination)
        return
    if root_config.is_file():
        _run(["mise", "trust", str(root_config)])
    _run(["mise", "trust", str(local_config)])
    _install_reana_dev(destination)
    reana_dev = destination / ".venv" / "bin" / "reana-dev"
    if not reana_dev.is_file():
        raise SrcdirError(f"Virtual environment repair did not create {reana_dev}.")


def _mise_environment_ready(destination: Path) -> bool:
    """Return whether the srcdir entry point refers to its current path."""
    environment = destination / ".venv"
    reana_dev = environment / "bin" / "reana-dev"
    if not reana_dev.is_file():
        return False
    try:
        entry_point = reana_dev.read_text(encoding="utf-8")[:1024]
    except (OSError, UnicodeDecodeError):
        return False
    return str(environment) in entry_point


def _discard_mise_environment(destination: Path) -> bool:
    """Remove a path-bound, derived mise virtual environment if present."""
    environment = destination / ".venv"
    if environment.is_symlink() or environment.is_file():
        environment.unlink()
        return True
    if environment.is_dir():
        shutil.rmtree(environment)
        return True
    return False


def _interactive_shell_arguments(
    destination: Path, marker: Dict, shell: str, *, login: bool = False
) -> List[str]:
    """Return a shell command that selects the srcdir's Python environment.

    Kitty and Tmux start managed sessions from long-lived processes whose
    environments may lack changes made by the user's login profile.  Start a
    login shell there; the session's pseudo-terminal makes it interactive.
    Plain shells inherit the caller's already-initialised environment instead.
    """
    shell_arguments = [shell, "-l" if login else "-i"]
    if marker.get("python_environment") == "mise":
        if shutil.which("mise") is None:
            raise SrcdirError(
                f"{destination} requires mise, but the mise executable is unavailable."
            )
        return ["mise", "exec", "-C", str(destination), "--", *shell_arguments]
    return shell_arguments


def _run_interactive(
    arguments: List[str], destination: Path, environment: Dict[str, str]
) -> None:
    """Run an interactive command without interpreting its eventual status."""
    subprocess.run(
        arguments,
        cwd=str(destination),
        env=environment,
        check=False,
    )


def _select_workspace_backend(requested_backend: Optional[str]) -> str:
    """Resolve an explicit backend or auto-detect when Click passes ``None``."""
    if requested_backend == "kitty":
        if shutil.which("kitten") is None:
            raise SrcdirError("--kitty requires the kitten executable.")
        if not os.environ.get("KITTY_LISTEN_ON"):
            raise SrcdirError(
                "--kitty requires Kitty remote control via KITTY_LISTEN_ON."
            )
        if _kitty_remote_tree() is None:
            raise SrcdirError(
                "--kitty cannot reach the Kitty remote-control endpoint in "
                "KITTY_LISTEN_ON."
            )
        return "kitty"
    if requested_backend is not None:
        return requested_backend
    if os.environ.get("TMUX"):
        return "tmux"
    if os.environ.get("KITTY_WINDOW_ID"):
        if _kitty_remote_tree() is not None:
            return "kitty"
        _echo_warning(
            "Kitty remote control is unavailable; opening a shell in the "
            "current terminal.",
        )
    return "plain"


@click.argument("name")
@click.option(
    "--srcdir-root",
    type=click.Path(file_okay=False),
    help=(
        "Directory containing managed source directories "
        "[optional; auto-discovered]."
    ),
)
@click.option(
    "--plain",
    "--no-kitty",
    "--no-tmux",
    "workspace_backend",
    flag_value="plain",
    help="Use the current terminal without a Kitty or Tmux session [optional].",
)
@click.option(
    "--kitty",
    "-k",
    "workspace_backend",
    flag_value="kitty",
    help="Use a dedicated Kitty session [optional; auto-detected].",
)
@click.option(
    "--tmux",
    "-t",
    "workspace_backend",
    flag_value="tmux",
    help="Use a dedicated Tmux session [optional; auto-detected].",
)
@srcdir_commands.command(name="srcdir-workon")
def srcdir_workon(
    name: str, srcdir_root: Optional[str], workspace_backend: Optional[str]
) -> None:
    """Open a shell for NAME using Kitty or Tmux when already inside either.

    Kitty requires a reachable remote-control endpoint. Tmux takes precedence
    if both environments are detected. Otherwise, open the shell in the current
    terminal.
    """
    _validate_name(name)
    _, managed_root = _resolve_context(
        srcdir_root_option=srcdir_root, require_source=False
    )
    destination = managed_root / name
    marker = _task_marker(destination)
    backend = _select_workspace_backend(workspace_backend)
    _ensure_mise_environment(destination, marker)
    shell = shutil.which(os.environ.get("SHELL", "sh"))
    if shell is None:
        raise SrcdirError("Cannot find the current shell executable.")
    shell_arguments = _interactive_shell_arguments(
        destination, marker, shell, login=backend != "plain"
    )

    if backend == "plain":
        _echo_heading(f"Opening shell for srcdir {name}")
        _echo_field("Location", str(destination))
        click.echo()
        click.echo("Exit the shell to return.")
        _run_interactive(shell_arguments, destination, os.environ.copy())
        return

    if backend == "kitty":
        kitty_tree = _kitty_remote_tree()
        if kitty_tree is None:
            raise SrcdirError(
                "Kitty remote control became unavailable before opening the session."
            )
        if _foreign_kitty_session(kitty_tree, name, destination):
            raise SrcdirError(
                f"Kitty session {name!r} is already open for something else. "
                "Close it, or rename the srcdir, before working on it."
            )
        running = str(destination) in _kitty_srcdir_sessions(kitty_tree)
        session_path = _ensure_kitty_session(destination, marker, shell_arguments)
        action = "Entering" if running else "Creating"
        _echo_heading(f"{action} Kitty session {name}")
        _run(
            [
                "kitten",
                "@",
                "--to",
                os.environ["KITTY_LISTEN_ON"],
                "action",
                "goto_session",
                str(session_path),
            ]
        )
        return

    if shutil.which("tmux") is None:
        if workspace_backend is None:
            raise SrcdirError(
                "TMUX is set, but the tmux executable is unavailable. "
                "Use --no-tmux to open a shell in the current terminal."
            )
        raise SrcdirError("--tmux requires the tmux executable.")

    session_name, session_id = _harmonise_tmux_session(
        destination, marker, _list_tmux_sessions()
    )
    if session_id is None:
        _echo_heading(f"Creating Tmux session {session_name}")
        tmux_shell_command = shlex.join(shell_arguments)
        result = _run(
            [
                "tmux",
                "new-session",
                "-d",
                "-P",
                "-F",
                "#{session_id}",
                "-s",
                session_name,
                "-c",
                str(destination),
                tmux_shell_command,
            ]
        )
        session_id = result.stdout.strip()
        if not session_id:
            raise SrcdirError(f"Cannot find newly created Tmux session {session_name}.")
        _mark_tmux_session(session_id, destination)

    _echo_heading(f"Entering Tmux session {session_name}")
    if os.environ.get("TMUX"):
        _run(["tmux", "switch-client", "-t", session_id])
    else:
        _run_interactive(
            ["tmux", "attach-session", "-t", session_id],
            destination,
            os.environ.copy(),
        )


def _update_renamed_srcdir_configuration(
    source: Path,
    destination: Path,
    marker: Dict,
    new_name: str,
    new_session_name: str,
    kitty_session_plan: Tuple[Path, Path, Optional[str], Optional[str]],
) -> None:
    """Update generated configuration after moving a managed srcdir."""
    mise_config_updated = False
    kitty_session_updated = False
    old_kitty_path, new_kitty_path, old_kitty_contents, new_kitty_contents = (
        kitty_session_plan
    )
    try:
        if marker.get("python_environment") == "mise":
            config_path = destination / MISE_LOCAL_CONFIG
            if config_path.is_file():
                try:
                    current_contents = config_path.read_text(encoding="utf-8")
                except OSError as error:
                    raise SrcdirError(f"Cannot read {config_path}: {error}") from error
                if _mise_config_is_generated(current_contents):
                    _write_mise_config(destination, overwrite=True)
                    mise_config_updated = True
                else:
                    _echo_warning(
                        f"Keeping the customised {config_path.name}; reana-dev "
                        "cannot update its virtual-environment prompt for the "
                        "new srcdir name.",
                    )
            else:
                _write_mise_config(destination)
                mise_config_updated = True
        if new_kitty_contents is not None:
            _write_kitty_session_contents(new_kitty_path, new_kitty_contents)
            try:
                old_kitty_path.unlink()
            except OSError as error:
                try:
                    new_kitty_path.unlink()
                except FileNotFoundError:
                    pass
                raise SrcdirError(
                    f"Cannot remove renamed Kitty session {old_kitty_path}: {error}"
                ) from error
            kitty_session_updated = True
        marker["name"] = new_name
        marker["kitty_session"] = str(new_kitty_path)
        marker["tmux_session"] = new_session_name
        _write_json(destination / SRCDIR_MARKER, marker)
    except click.ClickException as error:
        try:
            if kitty_session_updated:
                new_kitty_path.unlink()
                _write_kitty_session_contents(old_kitty_path, old_kitty_contents)
            destination.rename(source)
            if mise_config_updated:
                _write_mise_config(source, overwrite=True)
        except (OSError, click.ClickException) as rollback_error:
            raise SrcdirError(
                f"Cannot update the renamed srcdir configuration: {error}. "
                f"The rename also cannot be fully rolled back: "
                f"{rollback_error}."
            ) from rollback_error
        raise


@click.argument("new_name", metavar="NEW_NAME")
@click.argument("old_name", metavar="OLD_NAME")
@click.option(
    "--srcdir-root",
    type=click.Path(file_okay=False),
    help=(
        "Directory containing managed source directories "
        "[optional; auto-discovered]."
    ),
)
@click.option(
    "--kill-tmux",
    is_flag=True,
    help="Kill the associated Tmux session before renaming [optional].",
)
@click.option(
    "--kill-kitty",
    is_flag=True,
    help="Close the associated Kitty session before renaming [optional].",
)
@srcdir_commands.command(name="srcdir-rename")
def srcdir_rename(
    old_name: str,
    new_name: str,
    srcdir_root: Optional[str],
    kill_tmux: bool,
    kill_kitty: bool,
) -> None:
    """Rename OLD_NAME to NEW_NAME without changing its repositories."""
    _validate_name(old_name, "OLD_NAME")
    _validate_name(new_name, "NEW_NAME")
    if old_name == new_name:
        raise SrcdirError("OLD_NAME and NEW_NAME must be different.")
    _, managed_root = _resolve_context(
        srcdir_root_option=srcdir_root, require_source=False
    )
    source = managed_root / old_name
    destination = managed_root / new_name
    marker = _task_marker(source)
    if destination.exists():
        raise SrcdirError(f"Destination already exists: {destination}")

    if _is_within(Path.cwd().resolve(), source):
        raise SrcdirError(
            "Cannot rename a srcdir while working inside it. Exit its shell "
            "and run srcdir-rename from the canonical source directory, the "
            "srcdir root, or another srcdir."
        )

    sessions = _list_tmux_sessions()
    kitty_sessions = _list_kitty_sessions()
    if kitty_sessions is None:
        _warn_if_kitty_state_unknown(marker)
    current_session_name = marker.get("tmux_session")
    current_session = sessions.get(current_session_name)
    allow_unmarked_legacy = _legacy_tmux_session_name(
        marker["name"], current_session_name
    )
    current_session_id = (
        _owned_tmux_session_id(
            current_session_name,
            current_session,
            source,
            allow_unmarked_legacy=allow_unmarked_legacy,
        )
        if current_session
        and _tmux_session_is_owned(
            current_session,
            source,
            allow_unmarked_legacy=allow_unmarked_legacy,
        )
        else None
    )

    new_session_name = _tmux_session_name(
        new_name, existing_names=_allocated_tmux_names(managed_root, sessions)
    )
    target_session = sessions.get(new_session_name)
    if target_session and target_session[0] != current_session_id:
        raise SrcdirError(
            f"Cannot rename the srcdir because Tmux session "
            f"{new_session_name!r} is already in use."
        )
    if current_session_id:
        if not kill_tmux:
            raise SrcdirError(
                f"Tmux session {current_session_name} is running. Detach and "
                "pass --kill-tmux, or stop it manually."
            )
        if current_session_id == _current_tmux_session_id():
            raise SrcdirError(
                "Cannot rename a srcdir from its own Tmux session. Run "
                "srcdir-rename from the canonical source directory, the "
                "srcdir root, or another session."
            )

    kitty_running = kitty_sessions is not None and str(source) in kitty_sessions
    if kitty_running and not kill_kitty:
        raise SrcdirError(
            f"Kitty session {old_name} is running. Switch away and pass "
            "--kill-kitty, or stop it manually."
        )
    kitty_session_plan = _kitty_session_rename_plan(
        source, destination, marker, new_name
    )
    if current_session_id:
        _run(["tmux", "kill-session", "-t", current_session_id])
    if kitty_running:
        _close_kitty_session(source)

    _echo_heading(f"Renaming srcdir {old_name} to {new_name}")
    try:
        source.rename(destination)
    except OSError as error:
        raise SrcdirError(
            f"Cannot rename {source} to {destination}: {error}"
        ) from error

    _update_renamed_srcdir_configuration(
        source,
        destination,
        marker,
        new_name,
        new_session_name,
        kitty_session_plan,
    )

    discarded_environment = False
    if marker.get("python_environment") == "mise":
        try:
            discarded_environment = _discard_mise_environment(destination)
        except OSError as error:
            raise SrcdirError(
                f"Renamed the srcdir to {destination}, but cannot remove its "
                f"path-bound virtual environment: {error}. Remove "
                f"{destination / '.venv'} before working on it."
            ) from error

    click.echo()
    _echo_success(f"Renamed srcdir {old_name} to {new_name}")
    click.echo()
    _echo_field("Location", str(destination))
    if discarded_environment:
        _echo_field(
            "Environment",
            "discarded; srcdir-workon will recreate it",
        )
    click.echo()
    _echo_heading("Next steps:")
    _echo_command(f"reana-dev srcdir-workon {new_name}")


def _stash_ids(repository: Path) -> List[str]:
    """Return all stash object IDs from newest to oldest."""
    output = _git(repository, "stash", "list", "--format=%H")
    return [line for line in output.splitlines() if line]


def _retention_remotes(repository: Path) -> List[str]:
    """Return retention remotes that currently have tracking references."""
    reference_prefixes = {
        remote: f"refs/remotes/{remote}/" for remote in RETENTION_REMOTES
    }
    output = _git(
        repository,
        "for-each-ref",
        "--format=%(refname)",
        *(f"refs/remotes/{remote}" for remote in RETENTION_REMOTES),
    )
    references = output.splitlines()
    return [
        remote
        for remote, prefix in reference_prefixes.items()
        if any(reference.startswith(prefix) for reference in references)
    ]


def _repository_status(
    destination: Path,
    source_root: Path,
    initial_heads: Dict,
    repository_name: str,
) -> Dict:
    """Collect local state for one repository in a managed srcdir."""
    repository = destination / repository_name
    if not (repository / ".git").is_dir():
        return {"changed": 1, "dirty": 1, "stashes": 0, "unique": None}

    changed = int(
        _git(repository, "rev-parse", "HEAD") != initial_heads.get(repository_name)
    )
    dirty = int(bool(_git(repository, "status", "--porcelain")))
    unique_commits = _unique_commits(repository, _retention_remotes(repository))
    unique = len(unique_commits) if unique_commits is not None else None
    task_stashes = set(_stash_ids(repository))
    baseline_repository = source_root / repository_name
    baseline_stashes = (
        set(_stash_ids(baseline_repository))
        if (baseline_repository / ".git").is_dir()
        else set()
    )
    stashes = len(task_stashes.difference(baseline_stashes))
    return {
        "changed": changed,
        "dirty": dirty,
        "stashes": stashes,
        "unique": unique,
    }


def _source_directory_status(destination: Path, marker: Dict) -> Dict:
    """Collect concise status counts for one managed source directory."""
    initial_heads = marker.get("initial_heads", {})
    source_root = _required_marker_path(
        marker, "source_root", destination / SRCDIR_MARKER
    )
    repositories = marker.get("repositories", [])
    statuses = []
    if repositories:
        with futures.ThreadPoolExecutor(
            max_workers=min(8, len(repositories))
        ) as executor:
            tasks = [
                executor.submit(
                    _repository_status,
                    destination,
                    source_root,
                    initial_heads,
                    repository_name,
                )
                for repository_name in repositories
            ]
            statuses = [task.result() for task in tasks]

    if marker.get("python_environment") == "mise":
        venv = "ready" if _mise_environment_ready(destination) else "missing"
    else:
        venv = "-"
    unique_counts = [status["unique"] for status in statuses]
    return {
        "changed": sum(status["changed"] for status in statuses),
        "dirty": sum(status["dirty"] for status in statuses),
        "stashes": sum(status["stashes"] for status in statuses),
        "unique": (
            None
            if any(unique is None for unique in unique_counts)
            else sum(unique_counts)
        ),
        "venv": venv,
    }


def _render_table(headers: List[str], rows: List[List[str]]) -> None:
    """Render a compact plain-text table."""
    widths = [len(header) for header in headers]
    for row in rows:
        widths = [max(width, len(value)) for width, value in zip(widths, row)]
    click.echo("  ".join(header.ljust(width) for header, width in zip(headers, widths)))
    click.echo("  ".join("-" * width for width in widths))
    for row in rows:
        click.echo("  ".join(value.ljust(width) for value, width in zip(row, widths)))


@click.option(
    "--srcdir-root",
    type=click.Path(file_okay=False),
    help=(
        "Directory containing managed source directories "
        "[optional; auto-discovered]."
    ),
)
@srcdir_commands.command(name="srcdir-list")
def srcdir_list(srcdir_root: Optional[str]) -> None:
    """List managed source directories and their local state."""
    _, managed_root = _resolve_context(
        srcdir_root_option=srcdir_root, require_source=False
    )
    if not managed_root.is_dir():
        click.echo(f"No managed source directories in {managed_root}.")
        return
    sessions = _list_tmux_sessions()
    kitty_sessions = _list_kitty_sessions()
    rows = []
    errors = []
    for destination in sorted(managed_root.iterdir()):
        if not (destination / SRCDIR_MARKER).is_file():
            continue
        try:
            marker = _task_marker(destination)
            status = _source_directory_status(destination, marker)
        except Exception as error:
            rows.append([destination.name, "ERROR", "-", "-", "-", "-", "-", "-", "-"])
            errors.append((destination.name, str(error)))
            continue
        session_name = marker.get("tmux_session")
        session = sessions.get(session_name)
        if session is None:
            tmux_status = "stopped"
        else:
            try:
                _owned_tmux_session_id(
                    session_name,
                    session,
                    destination,
                    allow_unmarked_legacy=_legacy_tmux_session_name(
                        marker["name"], session_name
                    ),
                )
            except click.ClickException:
                tmux_status = "conflict"
            else:
                tmux_status = "running"
        rows.append(
            [
                marker["name"],
                marker.get("state", "unknown"),
                str(status["changed"]),
                str(status["dirty"]),
                str(status["unique"]) if status["unique"] is not None else "?",
                str(status["stashes"]),
                status["venv"],
                tmux_status,
                (
                    "-"
                    if kitty_sessions is None
                    else "running" if str(destination) in kitty_sessions else "stopped"
                ),
            ]
        )
    if not rows:
        click.echo(f"No managed source directories in {managed_root}.")
        return
    _render_table(
        [
            "NAME",
            "STATE",
            "CHANGED",
            "DIRTY",
            "UNIQUE",
            "STASHES",
            "VENV",
            "TMUX",
            "KITTY",
        ],
        rows,
    )
    if kitty_sessions is None:
        _echo_warning(
            "Kitty state unavailable; run srcdir-list from a Kitty window with "
            "remote control enabled."
        )
    for name, error in errors:
        _echo_warning(f"cannot inspect {name}: {error}")


def _refresh_audit_remotes(repository: Path, source_repository: Path) -> List[str]:
    """Refresh safe remotes and return those usable for retention checks."""
    usable_remotes = []
    remote_names = set(_git(repository, "remote").splitlines())
    if (source_repository / ".git").is_dir():
        if "local" in remote_names:
            _git(repository, "remote", "set-url", "local", str(source_repository))
        else:
            _git(repository, "remote", "add", "local", str(source_repository))
        result = _run(
            ["git", "fetch", "--quiet", "--prune", "local"],
            cwd=repository,
            check=False,
        )
        if result.returncode == 0:
            usable_remotes.append("local")

    for remote in RETENTION_REMOTES[1:]:
        if remote not in remote_names:
            continue
        result = _run(
            ["git", "fetch", "--quiet", "--prune", remote],
            cwd=repository,
            check=False,
        )
        if result.returncode == 0:
            usable_remotes.append(remote)
        else:
            _echo_warning(
                f"could not refresh {remote} in {repository.name}; "
                "its refs will not be treated as a backup.",
            )
    return usable_remotes


def _unique_commits(repository: Path, remotes: List[str]) -> Optional[List[str]]:
    """Return unretained commits, or ``None`` when no remote is verified."""
    if not remotes:
        return None
    arguments = ["log", "--oneline", "HEAD", "--branches", "--not"]
    arguments.extend(f"--remotes={remote}" for remote in remotes)
    output = _git(repository, *arguments)
    return [line for line in output.splitlines() if line]


def _audit_before_delete(destination: Path, marker: Dict) -> List[str]:
    """Return findings that make deletion potentially unsafe."""
    findings = []
    source_root = _required_marker_path(
        marker, "source_root", destination / SRCDIR_MARKER
    )
    if not source_root.is_dir():
        findings.append(
            f"Canonical source directory is missing: {source_root}; all stashes "
            "will be treated as unique."
        )

    for repository_name in marker.get("repositories", []):
        repository = destination / repository_name
        if not (repository / ".git").is_dir():
            findings.append(f"{repository_name}: repository is missing or invalid")
            continue
        dirty = _git(repository, "status", "--porcelain")
        if dirty:
            findings.append(f"{repository_name}: uncommitted files\n{dirty}")

        remotes = _refresh_audit_remotes(repository, source_root / repository_name)
        commits = _unique_commits(repository, remotes)
        if commits is None:
            findings.append(
                f"{repository_name}: no remote could be verified; treating all "
                "local commits as unretained"
            )
        elif commits:
            retention_sources = [
                "canonical" if remote == "local" else remote for remote in remotes
            ]
            findings.append(
                f"{repository_name}: commits not found in refreshed refs "
                f"({', '.join(retention_sources)})\n" + "\n".join(commits)
            )

        task_stashes = set(_stash_ids(repository))
        baseline_repository = source_root / repository_name
        baseline_stashes = (
            set(_stash_ids(baseline_repository))
            if (baseline_repository / ".git").is_dir()
            else set()
        )
        unique_stashes = task_stashes.difference(baseline_stashes)
        if unique_stashes:
            findings.append(
                f"{repository_name}: {len(unique_stashes)} stash(es) not retained "
                "in the canonical source directory"
            )
    return findings


def _trash_directory() -> Path:
    """Return the platform's user Trash directory."""
    if platform.system() == "Darwin":
        return Path.home() / ".Trash"
    data_home = Path(os.environ.get("XDG_DATA_HOME", Path.home() / ".local/share"))
    return data_home / "Trash" / "files"


def _trash_destination(destination: Path) -> Path:
    """Return a non-existing, timestamped Trash destination."""
    trash = _trash_directory()
    trash.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
    candidate = trash / f"{destination.name}-{timestamp}"
    suffix = 1
    while candidate.exists():
        candidate = trash / f"{destination.name}-{timestamp}-{suffix}"
        suffix += 1
    return candidate


def _current_tmux_session_id() -> Optional[str]:
    """Return the current Tmux session ID, if any."""
    if not os.environ.get("TMUX") or shutil.which("tmux") is None:
        return None
    result = _run(["tmux", "display-message", "-p", "#{session_id}"], check=False)
    return result.stdout.strip() if result.returncode == 0 else None


@click.argument("name")
@click.option(
    "--srcdir-root",
    type=click.Path(file_okay=False),
    help=(
        "Directory containing managed source directories "
        "[optional; auto-discovered]."
    ),
)
@click.option(
    "--kill-tmux",
    is_flag=True,
    help="Kill the associated Tmux session before teardown [optional].",
)
@click.option(
    "--kill-kitty",
    is_flag=True,
    help="Close the associated Kitty session before teardown [optional].",
)
@click.option(
    "--audit/--no-audit",
    default=True,
    help="Audit for unretained work before teardown [optional; default: audit].",
)
@click.option(
    "-y",
    "--yes",
    is_flag=True,
    help="Do not ask for final confirmation [optional].",
)
@srcdir_commands.command(name="srcdir-delete")
def srcdir_delete(
    name: str,
    srcdir_root: Optional[str],
    kill_tmux: bool,
    kill_kitty: bool,
    audit: bool,
    yes: bool,
) -> None:
    """Move NAME to Trash, auditing it by default."""
    _validate_name(name)
    _, managed_root = _resolve_context(
        srcdir_root_option=srcdir_root, require_source=False
    )
    destination = managed_root / name
    marker = _task_marker(destination)

    if _is_within(Path.cwd().resolve(), destination):
        raise SrcdirError(
            "Cannot delete a srcdir while working inside it. Exit its shell "
            "and run srcdir-delete from the canonical source directory, the "
            "srcdir root, or another srcdir."
        )

    session_name = marker.get("tmux_session")
    sessions = _list_tmux_sessions()
    kitty_sessions = _list_kitty_sessions()
    if kitty_sessions is None:
        _warn_if_kitty_state_unknown(marker)
    session = sessions.get(session_name)
    allow_unmarked_legacy = _legacy_tmux_session_name(marker["name"], session_name)
    session_id = (
        _owned_tmux_session_id(
            session_name,
            session,
            destination,
            allow_unmarked_legacy=allow_unmarked_legacy,
        )
        if session
        and _tmux_session_is_owned(
            session,
            destination,
            allow_unmarked_legacy=allow_unmarked_legacy,
        )
        else None
    )
    if session_id:
        if not kill_tmux:
            raise SrcdirError(
                f"Tmux session {session_name} is running. Detach and pass "
                "--kill-tmux, or stop it manually."
            )
        if session_id == _current_tmux_session_id():
            raise SrcdirError(
                "Cannot delete a srcdir from its own Tmux session. Run "
                "srcdir-delete from the baseline or another session."
            )

    kitty_running = kitty_sessions is not None and str(destination) in kitty_sessions
    if kitty_running:
        if not kill_kitty:
            raise SrcdirError(
                f"Kitty session {name} is running. Switch away and pass "
                "--kill-kitty, or stop it manually."
            )
    kitty_session_path = _marker_kitty_session_path(marker)
    _validate_kitty_session_file(kitty_session_path, destination)

    if audit:
        _echo_heading(f"Auditing srcdir {name}")
        _echo_field("Location", str(destination))
        findings = _audit_before_delete(destination, marker)
        if findings:
            _echo_warning("Teardown audit found unretained work:")
            for finding in findings:
                click.echo(f"\n{finding}")
            raise SrcdirError(
                "Refusing teardown. Preserve the reported work or repeat with "
                "--no-audit."
            )
        _echo_success("Teardown audit found no unretained work")
    else:
        _echo_heading(f"Skipping teardown audit for srcdir {name}")
        _echo_field("Location", str(destination))
        _echo_warning("Unretained work may be present")

    if not yes and not click.confirm(f"Move {destination} to Trash?"):
        raise click.Abort()
    if session_id:
        _run(["tmux", "kill-session", "-t", session_id])
    if kitty_running:
        _close_kitty_session(destination)
    _remove_kitty_session_file(kitty_session_path, destination)

    trash_destination = _trash_destination(destination)
    _echo_heading(f"Moving srcdir {name} to Trash")
    shutil.move(str(destination), str(trash_destination))
    click.echo()
    _echo_success(f"Moved srcdir {name} to Trash")
    click.echo()
    _echo_field("Location", str(trash_destination))


srcdir_commands_list = list(srcdir_commands.commands.values())
