# This file is part of REANA.
# Copyright (C) 2020, 2022 CERN.
#
# REANA is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: Docker build

on:
  workflow_call:

jobs:

  docker-build:
    runs-on: ubuntu-20.04
    steps:
      - name: "⏬ Checkout"
        uses: actions/checkout@v3
      - name: "🏗️ Build Docker image"
        run: ./run-tests.sh --check-docker-build
