# This file is part of REANA.
# Copyright (C) 2020, 2022 CERN.
#
# REANA is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: Python test

on:
  workflow_call:
    inputs:
      python-versions:
        description: "Array of Python versions"
        default: "['3.8']"
        required: false
        type: string
    secrets:
      codecov-token:
        required: true

jobs:

  python-test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ${{ fromJSON(inputs.python-versions) }}
    steps:
      - name: "⏬ Checkout"
        uses: actions/checkout@v3
      - name: "🐍 Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: "🐍 Install Python dependencies"
        run: |
          pip install --upgrade pip setuptools py
          pip install twine wheel
          pip install .[all]
      - name: "⚙️ Run pytest"
        run: ./run-tests.sh --check-pytest
      - name: "☂️ Codecov Coverage"
        uses: codecov/codecov-action@v3
        if: ${{ matrix.python-version == fromJSON(inputs.python-versions)[0] }}
        with:
          token: ${{ secrets.codecov-token }}
          files: coverage.xml
